name: CI/CD Backend - Tienda Perritos

on:
  push:
    branches:
      - deploy
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t tienda-backend ./backend

      - name: Tag and push to ECR
        run: |
          docker tag tienda-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_BACKEND_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:latest",
              "docker stop tienda-backend || true",
              "docker rm tienda-backend || true",
              "docker run -d --name tienda-backend -p 3001:3001 --restart unless-stopped -e DB_HOST=${{ secrets.EC2_DB_PRIVATE_IP }} -e DB_USER=root -e DB_PASSWORD=admin123 -e DB_NAME=tienda_perritos -e DB_PORT=3306 ${{ secrets.ECR_REPO_URL_BACKEND }}:latest"
            ]'
